/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.15.8
 * source: GammaProto.proto
 * git: https://github.com/thesayyn/protoc-gen-ts
 * buymeacoffee: https://www.buymeacoffee.com/thesayyn
 *  */
import * as pb_1 from "google-protobuf";
export var Fields;
(function (Fields) {
    Fields[Fields["none"] = 0] = "none";
    Fields[Fields["turn"] = 1] = "turn";
    Fields[Fields["update"] = 2] = "update";
    Fields[Fields["reveal"] = 3] = "reveal";
    Fields[Fields["add"] = 4] = "add";
    Fields[Fields["del"] = 5] = "del";
    Fields[Fields["timages"] = 21] = "timages";
    Fields[Fields["mimages"] = 22] = "mimages";
})(Fields || (Fields = {}));
export class Iloc extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("y" in data && data.y != undefined) {
                this.y = data.y;
            }
            if ("x" in data && data.x != undefined) {
                this.x = data.x;
            }
        }
    }
    get y() {
        return pb_1.Message.getField(this, 1);
    }
    set y(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get x() {
        return pb_1.Message.getField(this, 2);
    }
    set x(value) {
        pb_1.Message.setField(this, 2, value);
    }
    toObject() {
        const data = {};
        if (this.y != null) {
            data.y = this.y;
        }
        if (this.x != null) {
            data.x = this.x;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.y !== undefined)
            writer.writeInt32(1, this.y);
        if (this.x !== undefined)
            writer.writeInt32(2, this.x);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Iloc();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.y = reader.readInt32();
                    break;
                case 2:
                    message.x = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return Iloc.deserialize(bytes);
    }
}
export class Floc extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("y" in data && data.y != undefined) {
                this.y = data.y;
            }
            if ("x" in data && data.x != undefined) {
                this.x = data.x;
            }
        }
    }
    get y() {
        return pb_1.Message.getField(this, 1);
    }
    set y(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get x() {
        return pb_1.Message.getField(this, 2);
    }
    set x(value) {
        pb_1.Message.setField(this, 2, value);
    }
    toObject() {
        const data = {};
        if (this.y != null) {
            data.y = this.y;
        }
        if (this.x != null) {
            data.x = this.x;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.y !== undefined)
            writer.writeFloat(1, this.y);
        if (this.x !== undefined)
            writer.writeFloat(2, this.x);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Floc();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.y = reader.readFloat();
                    break;
                case 2:
                    message.x = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return Floc.deserialize(bytes);
    }
}
export class IDloc extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("dy" in data && data.dy != undefined) {
                this.dy = data.dy;
            }
            if ("dx" in data && data.dx != undefined) {
                this.dx = data.dx;
            }
        }
    }
    get dy() {
        return pb_1.Message.getField(this, 1);
    }
    set dy(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get dx() {
        return pb_1.Message.getField(this, 2);
    }
    set dx(value) {
        pb_1.Message.setField(this, 2, value);
    }
    toObject() {
        const data = {};
        if (this.dy != null) {
            data.dy = this.dy;
        }
        if (this.dx != null) {
            data.dx = this.dx;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.dy !== undefined)
            writer.writeInt32(1, this.dy);
        if (this.dx !== undefined)
            writer.writeInt32(2, this.dx);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new IDloc();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.dy = reader.readInt32();
                    break;
                case 2:
                    message.dx = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return IDloc.deserialize(bytes);
    }
}
export class FDloc extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("dy" in data && data.dy != undefined) {
                this.dy = data.dy;
            }
            if ("dx" in data && data.dx != undefined) {
                this.dx = data.dx;
            }
        }
    }
    get dy() {
        return pb_1.Message.getField(this, 1);
    }
    set dy(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get dx() {
        return pb_1.Message.getField(this, 2);
    }
    set dx(value) {
        pb_1.Message.setField(this, 2, value);
    }
    toObject() {
        const data = {};
        if (this.dy != null) {
            data.dy = this.dy;
        }
        if (this.dx != null) {
            data.dx = this.dx;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.dy !== undefined)
            writer.writeFloat(1, this.dy);
        if (this.dx !== undefined)
            writer.writeFloat(2, this.dx);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FDloc();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.dy = reader.readFloat();
                    break;
                case 2:
                    message.dx = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return FDloc.deserialize(bytes);
    }
}
export class Dloc extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("dy_dt" in data && data.dy_dt != undefined) {
                this.dy_dt = data.dy_dt;
            }
            if ("dx_dt" in data && data.dx_dt != undefined) {
                this.dx_dt = data.dx_dt;
            }
        }
    }
    get dy_dt() {
        return pb_1.Message.getField(this, 1);
    }
    set dy_dt(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get dx_dt() {
        return pb_1.Message.getField(this, 2);
    }
    set dx_dt(value) {
        pb_1.Message.setField(this, 2, value);
    }
    toObject() {
        const data = {};
        if (this.dy_dt != null) {
            data.dy_dt = this.dy_dt;
        }
        if (this.dx_dt != null) {
            data.dx_dt = this.dx_dt;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.dy_dt !== undefined)
            writer.writeFloat(1, this.dy_dt);
        if (this.dx_dt !== undefined)
            writer.writeFloat(2, this.dx_dt);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Dloc();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.dy_dt = reader.readFloat();
                    break;
                case 2:
                    message.dx_dt = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return Dloc.deserialize(bytes);
    }
}
export class Turn extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
        }
    }
    get id() {
        return pb_1.Message.getField(this, 1);
    }
    set id(value) {
        pb_1.Message.setField(this, 1, value);
    }
    toObject() {
        const data = {};
        if (this.id != null) {
            data.id = this.id;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id !== undefined)
            writer.writeUint32(1, this.id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Turn();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return Turn.deserialize(bytes);
    }
}
export class AMessage extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("turn" in data && data.turn != undefined) {
                this.turn = data.turn;
            }
            if ("updates" in data && data.updates != undefined) {
                this.updates = data.updates;
            }
            if ("reveals" in data && data.reveals != undefined) {
                this.reveals = data.reveals;
            }
            if ("adds" in data && data.adds != undefined) {
                this.adds = data.adds;
            }
            if ("dels" in data && data.dels != undefined) {
                this.dels = data.dels;
            }
            if ("ter_images" in data && data.ter_images != undefined) {
                this.ter_images = data.ter_images;
            }
            if ("mod_images" in data && data.mod_images != undefined) {
                this.mod_images = data.mod_images;
            }
        }
    }
    get turn() {
        return pb_1.Message.getWrapperField(this, Turn, 1);
    }
    set turn(value) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get updates() {
        return pb_1.Message.getWrapperField(this, UpdateSeq, 2);
    }
    set updates(value) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    get reveals() {
        return pb_1.Message.getWrapperField(this, RevealSeq, 3);
    }
    set reveals(value) {
        pb_1.Message.setWrapperField(this, 3, value);
    }
    get adds() {
        return pb_1.Message.getWrapperField(this, AddSeq, 4);
    }
    set adds(value) {
        pb_1.Message.setWrapperField(this, 4, value);
    }
    get dels() {
        return pb_1.Message.getWrapperField(this, DelSeq, 5);
    }
    set dels(value) {
        pb_1.Message.setWrapperField(this, 5, value);
    }
    get ter_images() {
        return pb_1.Message.getWrapperField(this, TerImageSeq, 21);
    }
    set ter_images(value) {
        pb_1.Message.setWrapperField(this, 21, value);
    }
    get mod_images() {
        return pb_1.Message.getWrapperField(this, ModImageSeq, 22);
    }
    set mod_images(value) {
        pb_1.Message.setWrapperField(this, 22, value);
    }
    toObject() {
        const data = {};
        if (this.turn != null) {
            data.turn = this.turn.toObject();
        }
        if (this.updates != null) {
            data.updates = this.updates.toObject();
        }
        if (this.reveals != null) {
            data.reveals = this.reveals.toObject();
        }
        if (this.adds != null) {
            data.adds = this.adds.toObject();
        }
        if (this.dels != null) {
            data.dels = this.dels.toObject();
        }
        if (this.ter_images != null) {
            data.ter_images = this.ter_images.toObject();
        }
        if (this.mod_images != null) {
            data.mod_images = this.mod_images.toObject();
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.turn !== undefined)
            writer.writeMessage(1, this.turn, () => this.turn.serialize(writer));
        if (this.updates !== undefined)
            writer.writeMessage(2, this.updates, () => this.updates.serialize(writer));
        if (this.reveals !== undefined)
            writer.writeMessage(3, this.reveals, () => this.reveals.serialize(writer));
        if (this.adds !== undefined)
            writer.writeMessage(4, this.adds, () => this.adds.serialize(writer));
        if (this.dels !== undefined)
            writer.writeMessage(5, this.dels, () => this.dels.serialize(writer));
        if (this.ter_images !== undefined)
            writer.writeMessage(21, this.ter_images, () => this.ter_images.serialize(writer));
        if (this.mod_images !== undefined)
            writer.writeMessage(22, this.mod_images, () => this.mod_images.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.turn, () => message.turn = Turn.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.updates, () => message.updates = UpdateSeq.deserialize(reader));
                    break;
                case 3:
                    reader.readMessage(message.reveals, () => message.reveals = RevealSeq.deserialize(reader));
                    break;
                case 4:
                    reader.readMessage(message.adds, () => message.adds = AddSeq.deserialize(reader));
                    break;
                case 5:
                    reader.readMessage(message.dels, () => message.dels = DelSeq.deserialize(reader));
                    break;
                case 21:
                    reader.readMessage(message.ter_images, () => message.ter_images = TerImageSeq.deserialize(reader));
                    break;
                case 22:
                    reader.readMessage(message.mod_images, () => message.mod_images = ModImageSeq.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return AMessage.deserialize(bytes);
    }
}
export class Update extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
            if ("hp" in data && data.hp != undefined) {
                this.hp = data.hp;
            }
            if ("isHp" in data && data.isHp != undefined) {
                this.isHp = data.isHp;
            }
            if ("floc" in data && data.floc != undefined) {
                this.floc = data.floc;
            }
            if ("is_floc" in data && data.is_floc != undefined) {
                this.is_floc = data.is_floc;
            }
            if ("iloc" in data && data.iloc != undefined) {
                this.iloc = data.iloc;
            }
            if ("is_iloc" in data && data.is_iloc != undefined) {
                this.is_iloc = data.is_iloc;
            }
            if ("dloc" in data && data.dloc != undefined) {
                this.dloc = data.dloc;
            }
            if ("is_dloc" in data && data.is_dloc != undefined) {
                this.is_dloc = data.is_dloc;
            }
            if ("player_id" in data && data.player_id != undefined) {
                this.player_id = data.player_id;
            }
            if ("quality" in data && data.quality != undefined) {
                this.quality = data.quality;
            }
        }
    }
    get id() {
        return pb_1.Message.getField(this, 1);
    }
    set id(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get hp() {
        return pb_1.Message.getField(this, 2);
    }
    set hp(value) {
        pb_1.Message.setField(this, 2, value);
    }
    get isHp() {
        return pb_1.Message.getField(this, 3);
    }
    set isHp(value) {
        pb_1.Message.setField(this, 3, value);
    }
    get floc() {
        return pb_1.Message.getWrapperField(this, Floc, 4);
    }
    set floc(value) {
        pb_1.Message.setWrapperField(this, 4, value);
    }
    get is_floc() {
        return pb_1.Message.getField(this, 5);
    }
    set is_floc(value) {
        pb_1.Message.setField(this, 5, value);
    }
    get iloc() {
        return pb_1.Message.getWrapperField(this, Iloc, 6);
    }
    set iloc(value) {
        pb_1.Message.setWrapperField(this, 6, value);
    }
    get is_iloc() {
        return pb_1.Message.getField(this, 7);
    }
    set is_iloc(value) {
        pb_1.Message.setField(this, 7, value);
    }
    get dloc() {
        return pb_1.Message.getWrapperField(this, Dloc, 8);
    }
    set dloc(value) {
        pb_1.Message.setWrapperField(this, 8, value);
    }
    get is_dloc() {
        return pb_1.Message.getField(this, 9);
    }
    set is_dloc(value) {
        pb_1.Message.setField(this, 9, value);
    }
    get player_id() {
        return pb_1.Message.getField(this, 10);
    }
    set player_id(value) {
        pb_1.Message.setField(this, 10, value);
    }
    get quality() {
        return pb_1.Message.getField(this, 11);
    }
    set quality(value) {
        pb_1.Message.setField(this, 11, value);
    }
    toObject() {
        const data = {};
        if (this.id != null) {
            data.id = this.id;
        }
        if (this.hp != null) {
            data.hp = this.hp;
        }
        if (this.isHp != null) {
            data.isHp = this.isHp;
        }
        if (this.floc != null) {
            data.floc = this.floc.toObject();
        }
        if (this.is_floc != null) {
            data.is_floc = this.is_floc;
        }
        if (this.iloc != null) {
            data.iloc = this.iloc.toObject();
        }
        if (this.is_iloc != null) {
            data.is_iloc = this.is_iloc;
        }
        if (this.dloc != null) {
            data.dloc = this.dloc.toObject();
        }
        if (this.is_dloc != null) {
            data.is_dloc = this.is_dloc;
        }
        if (this.player_id != null) {
            data.player_id = this.player_id;
        }
        if (this.quality != null) {
            data.quality = this.quality;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id !== undefined)
            writer.writeUint32(1, this.id);
        if (this.hp !== undefined)
            writer.writeInt32(2, this.hp);
        if (this.isHp !== undefined)
            writer.writeBool(3, this.isHp);
        if (this.floc !== undefined)
            writer.writeMessage(4, this.floc, () => this.floc.serialize(writer));
        if (this.is_floc !== undefined)
            writer.writeBool(5, this.is_floc);
        if (this.iloc !== undefined)
            writer.writeMessage(6, this.iloc, () => this.iloc.serialize(writer));
        if (this.is_iloc !== undefined)
            writer.writeBool(7, this.is_iloc);
        if (this.dloc !== undefined)
            writer.writeMessage(8, this.dloc, () => this.dloc.serialize(writer));
        if (this.is_dloc !== undefined)
            writer.writeBool(9, this.is_dloc);
        if (this.player_id !== undefined)
            writer.writeUint32(10, this.player_id);
        if (this.quality !== undefined)
            writer.writeFloat(11, this.quality);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Update();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readUint32();
                    break;
                case 2:
                    message.hp = reader.readInt32();
                    break;
                case 3:
                    message.isHp = reader.readBool();
                    break;
                case 4:
                    reader.readMessage(message.floc, () => message.floc = Floc.deserialize(reader));
                    break;
                case 5:
                    message.is_floc = reader.readBool();
                    break;
                case 6:
                    reader.readMessage(message.iloc, () => message.iloc = Iloc.deserialize(reader));
                    break;
                case 7:
                    message.is_iloc = reader.readBool();
                    break;
                case 8:
                    reader.readMessage(message.dloc, () => message.dloc = Dloc.deserialize(reader));
                    break;
                case 9:
                    message.is_dloc = reader.readBool();
                    break;
                case 10:
                    message.player_id = reader.readUint32();
                    break;
                case 11:
                    message.quality = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return Update.deserialize(bytes);
    }
}
export class UpdateSeq extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("updates" in data && data.updates != undefined) {
                this.updates = data.updates;
            }
        }
    }
    get updates() {
        return pb_1.Message.getRepeatedWrapperField(this, Update, 1);
    }
    set updates(value) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    toObject() {
        const data = {};
        if (this.updates != null) {
            data.updates = this.updates.map((item) => item.toObject());
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.updates !== undefined)
            writer.writeRepeatedMessage(1, this.updates, (item) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateSeq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.updates, () => pb_1.Message.addToRepeatedWrapperField(message, 1, Update.deserialize(reader), Update));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return UpdateSeq.deserialize(bytes);
    }
}
export class Ident extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
            if ("type" in data && data.type != undefined) {
                this.type = data.type;
            }
            if ("i_ndx" in data && data.i_ndx != undefined) {
                this.i_ndx = data.i_ndx;
            }
            if ("m_ndx" in data && data.m_ndx != undefined) {
                this.m_ndx = data.m_ndx;
            }
            if ("display" in data && data.display != undefined) {
                this.display = data.display;
            }
            if ("player_id" in data && data.player_id != undefined) {
                this.player_id = data.player_id;
            }
        }
    }
    get id() {
        return pb_1.Message.getField(this, 1);
    }
    set id(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get type() {
        return pb_1.Message.getField(this, 2);
    }
    set type(value) {
        pb_1.Message.setField(this, 2, value);
    }
    get i_ndx() {
        return pb_1.Message.getField(this, 3);
    }
    set i_ndx(value) {
        pb_1.Message.setField(this, 3, value);
    }
    get m_ndx() {
        return pb_1.Message.getField(this, 4);
    }
    set m_ndx(value) {
        pb_1.Message.setField(this, 4, value);
    }
    get display() {
        return pb_1.Message.getField(this, 8);
    }
    set display(value) {
        pb_1.Message.setField(this, 8, value);
    }
    get player_id() {
        return pb_1.Message.getField(this, 10);
    }
    set player_id(value) {
        pb_1.Message.setField(this, 10, value);
    }
    toObject() {
        const data = {};
        if (this.id != null) {
            data.id = this.id;
        }
        if (this.type != null) {
            data.type = this.type;
        }
        if (this.i_ndx != null) {
            data.i_ndx = this.i_ndx;
        }
        if (this.m_ndx != null) {
            data.m_ndx = this.m_ndx;
        }
        if (this.display != null) {
            data.display = this.display;
        }
        if (this.player_id != null) {
            data.player_id = this.player_id;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id !== undefined)
            writer.writeUint32(1, this.id);
        if (typeof this.type === "string" && this.type.length)
            writer.writeString(2, this.type);
        if (this.i_ndx !== undefined)
            writer.writeUint32(3, this.i_ndx);
        if (this.m_ndx !== undefined)
            writer.writeUint32(4, this.m_ndx);
        if (typeof this.display === "string" && this.display.length)
            writer.writeString(8, this.display);
        if (this.player_id !== undefined)
            writer.writeUint32(10, this.player_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Ident();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readUint32();
                    break;
                case 2:
                    message.type = reader.readString();
                    break;
                case 3:
                    message.i_ndx = reader.readUint32();
                    break;
                case 4:
                    message.m_ndx = reader.readUint32();
                    break;
                case 8:
                    message.display = reader.readString();
                    break;
                case 10:
                    message.player_id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return Ident.deserialize(bytes);
    }
}
export class Add extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("ident" in data && data.ident != undefined) {
                this.ident = data.ident;
            }
            if ("update" in data && data.update != undefined) {
                this.update = data.update;
            }
        }
    }
    get ident() {
        return pb_1.Message.getWrapperField(this, Ident, 1);
    }
    set ident(value) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get update() {
        return pb_1.Message.getWrapperField(this, Update, 2);
    }
    set update(value) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    toObject() {
        const data = {};
        if (this.ident != null) {
            data.ident = this.ident.toObject();
        }
        if (this.update != null) {
            data.update = this.update.toObject();
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.ident !== undefined)
            writer.writeMessage(1, this.ident, () => this.ident.serialize(writer));
        if (this.update !== undefined)
            writer.writeMessage(2, this.update, () => this.update.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Add();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.ident, () => message.ident = Ident.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.update, () => message.update = Update.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return Add.deserialize(bytes);
    }
}
export class AddSeq extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("adds" in data && data.adds != undefined) {
                this.adds = data.adds;
            }
        }
    }
    get adds() {
        return pb_1.Message.getRepeatedWrapperField(this, Add, 1);
    }
    set adds(value) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    toObject() {
        const data = {};
        if (this.adds != null) {
            data.adds = this.adds.map((item) => item.toObject());
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.adds !== undefined)
            writer.writeRepeatedMessage(1, this.adds, (item) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AddSeq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.adds, () => pb_1.Message.addToRepeatedWrapperField(message, 1, Add.deserialize(reader), Add));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return AddSeq.deserialize(bytes);
    }
}
export class Del extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
        }
    }
    get id() {
        return pb_1.Message.getField(this, 2);
    }
    set id(value) {
        pb_1.Message.setField(this, 2, value);
    }
    toObject() {
        const data = {};
        if (this.id != null) {
            data.id = this.id;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id !== undefined)
            writer.writeUint32(2, this.id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Del();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 2:
                    message.id = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return Del.deserialize(bytes);
    }
}
export class DelSeq extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("dels" in data && data.dels != undefined) {
                this.dels = data.dels;
            }
        }
    }
    get dels() {
        return pb_1.Message.getRepeatedWrapperField(this, Del, 1);
    }
    set dels(value) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    toObject() {
        const data = {};
        if (this.dels != null) {
            data.dels = this.dels.map((item) => item.toObject());
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.dels !== undefined)
            writer.writeRepeatedMessage(1, this.dels, (item) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DelSeq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.dels, () => pb_1.Message.addToRepeatedWrapperField(message, 1, Del.deserialize(reader), Del));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return DelSeq.deserialize(bytes);
    }
}
export class TerRunX extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("dx" in data && data.dx != undefined) {
                this.dx = data.dx;
            }
            if ("ztv" in data && data.ztv != undefined) {
                this.ztv = data.ztv;
            }
        }
    }
    get dx() {
        return pb_1.Message.getField(this, 2);
    }
    set dx(value) {
        pb_1.Message.setField(this, 2, value);
    }
    get ztv() {
        return pb_1.Message.getField(this, 3);
    }
    set ztv(value) {
        pb_1.Message.setField(this, 3, value);
    }
    toObject() {
        const data = {};
        if (this.dx != null) {
            data.dx = this.dx;
        }
        if (this.ztv != null) {
            data.ztv = this.ztv;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.dx !== undefined)
            writer.writeInt32(2, this.dx);
        if (this.ztv !== undefined)
            writer.writeInt32(3, this.ztv);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TerRunX();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 2:
                    message.dx = reader.readInt32();
                    break;
                case 3:
                    message.ztv = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return TerRunX.deserialize(bytes);
    }
}
export class TerRowY extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("loc" in data && data.loc != undefined) {
                this.loc = data.loc;
            }
            if ("runx" in data && data.runx != undefined) {
                this.runx = data.runx;
            }
        }
    }
    get loc() {
        return pb_1.Message.getWrapperField(this, Iloc, 1);
    }
    set loc(value) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get runx() {
        return pb_1.Message.getRepeatedWrapperField(this, TerRunX, 2);
    }
    set runx(value) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    toObject() {
        const data = {};
        if (this.loc != null) {
            data.loc = this.loc.toObject();
        }
        if (this.runx != null) {
            data.runx = this.runx.map((item) => item.toObject());
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.loc !== undefined)
            writer.writeMessage(1, this.loc, () => this.loc.serialize(writer));
        if (this.runx !== undefined)
            writer.writeRepeatedMessage(2, this.runx, (item) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TerRowY();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.loc, () => message.loc = Iloc.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.runx, () => pb_1.Message.addToRepeatedWrapperField(message, 2, TerRunX.deserialize(reader), TerRunX));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return TerRowY.deserialize(bytes);
    }
}
export class RevealSeq extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("rowy" in data && data.rowy != undefined) {
                this.rowy = data.rowy;
            }
        }
    }
    get rowy() {
        return pb_1.Message.getRepeatedWrapperField(this, TerRowY, 1);
    }
    set rowy(value) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    toObject() {
        const data = {};
        if (this.rowy != null) {
            data.rowy = this.rowy.map((item) => item.toObject());
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.rowy !== undefined)
            writer.writeRepeatedMessage(1, this.rowy, (item) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RevealSeq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.rowy, () => pb_1.Message.addToRepeatedWrapperField(message, 1, TerRowY.deserialize(reader), TerRowY));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return RevealSeq.deserialize(bytes);
    }
}
export class SubImage extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("y0" in data && data.y0 != undefined) {
                this.y0 = data.y0;
            }
            if ("x0" in data && data.x0 != undefined) {
                this.x0 = data.x0;
            }
            if ("y_px" in data && data.y_px != undefined) {
                this.y_px = data.y_px;
            }
            if ("x_px" in data && data.x_px != undefined) {
                this.x_px = data.x_px;
            }
            if ("y_off" in data && data.y_off != undefined) {
                this.y_off = data.y_off;
            }
            if ("x_off" in data && data.x_off != undefined) {
                this.x_off = data.x_off;
            }
            if ("alt_url" in data && data.alt_url != undefined) {
                this.alt_url = data.alt_url;
            }
        }
    }
    get y0() {
        return pb_1.Message.getField(this, 2);
    }
    set y0(value) {
        pb_1.Message.setField(this, 2, value);
    }
    get x0() {
        return pb_1.Message.getField(this, 3);
    }
    set x0(value) {
        pb_1.Message.setField(this, 3, value);
    }
    get y_px() {
        return pb_1.Message.getField(this, 4);
    }
    set y_px(value) {
        pb_1.Message.setField(this, 4, value);
    }
    get x_px() {
        return pb_1.Message.getField(this, 5);
    }
    set x_px(value) {
        pb_1.Message.setField(this, 5, value);
    }
    get y_off() {
        return pb_1.Message.getField(this, 6);
    }
    set y_off(value) {
        pb_1.Message.setField(this, 6, value);
    }
    get x_off() {
        return pb_1.Message.getField(this, 7);
    }
    set x_off(value) {
        pb_1.Message.setField(this, 7, value);
    }
    get alt_url() {
        return pb_1.Message.getField(this, 8);
    }
    set alt_url(value) {
        pb_1.Message.setField(this, 8, value);
    }
    toObject() {
        const data = {};
        if (this.y0 != null) {
            data.y0 = this.y0;
        }
        if (this.x0 != null) {
            data.x0 = this.x0;
        }
        if (this.y_px != null) {
            data.y_px = this.y_px;
        }
        if (this.x_px != null) {
            data.x_px = this.x_px;
        }
        if (this.y_off != null) {
            data.y_off = this.y_off;
        }
        if (this.x_off != null) {
            data.x_off = this.x_off;
        }
        if (this.alt_url != null) {
            data.alt_url = this.alt_url;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.y0 !== undefined)
            writer.writeUint32(2, this.y0);
        if (this.x0 !== undefined)
            writer.writeUint32(3, this.x0);
        if (this.y_px !== undefined)
            writer.writeUint32(4, this.y_px);
        if (this.x_px !== undefined)
            writer.writeUint32(5, this.x_px);
        if (this.y_off !== undefined)
            writer.writeUint32(6, this.y_off);
        if (this.x_off !== undefined)
            writer.writeUint32(7, this.x_off);
        if (typeof this.alt_url === "string" && this.alt_url.length)
            writer.writeString(8, this.alt_url);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SubImage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 2:
                    message.y0 = reader.readUint32();
                    break;
                case 3:
                    message.x0 = reader.readUint32();
                    break;
                case 4:
                    message.y_px = reader.readUint32();
                    break;
                case 5:
                    message.x_px = reader.readUint32();
                    break;
                case 6:
                    message.y_off = reader.readUint32();
                    break;
                case 7:
                    message.x_off = reader.readUint32();
                    break;
                case 8:
                    message.alt_url = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return SubImage.deserialize(bytes);
    }
}
export class ImageAry extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("npixels" in data && data.npixels != undefined) {
                this.npixels = data.npixels;
            }
            if ("nrows" in data && data.nrows != undefined) {
                this.nrows = data.nrows;
            }
            if ("ncols" in data && data.ncols != undefined) {
                this.ncols = data.ncols;
            }
            if ("url" in data && data.url != undefined) {
                this.url = data.url;
            }
        }
    }
    get npixels() {
        return pb_1.Message.getField(this, 1);
    }
    set npixels(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get nrows() {
        return pb_1.Message.getField(this, 2);
    }
    set nrows(value) {
        pb_1.Message.setField(this, 2, value);
    }
    get ncols() {
        return pb_1.Message.getField(this, 3);
    }
    set ncols(value) {
        pb_1.Message.setField(this, 3, value);
    }
    get url() {
        return pb_1.Message.getField(this, 4);
    }
    set url(value) {
        pb_1.Message.setField(this, 4, value);
    }
    toObject() {
        const data = {};
        if (this.npixels != null) {
            data.npixels = this.npixels;
        }
        if (this.nrows != null) {
            data.nrows = this.nrows;
        }
        if (this.ncols != null) {
            data.ncols = this.ncols;
        }
        if (this.url != null) {
            data.url = this.url;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.npixels !== undefined)
            writer.writeUint32(1, this.npixels);
        if (this.nrows !== undefined)
            writer.writeUint32(2, this.nrows);
        if (this.ncols !== undefined)
            writer.writeUint32(3, this.ncols);
        if (typeof this.url === "string" && this.url.length)
            writer.writeString(4, this.url);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ImageAry();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.npixels = reader.readUint32();
                    break;
                case 2:
                    message.nrows = reader.readUint32();
                    break;
                case 3:
                    message.ncols = reader.readUint32();
                    break;
                case 4:
                    message.url = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return ImageAry.deserialize(bytes);
    }
}
export class TerImage extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("tvid" in data && data.tvid != undefined) {
                this.tvid = data.tvid;
            }
            if ("name" in data && data.name != undefined) {
                this.name = data.name;
            }
            if ("sub_image" in data && data.sub_image != undefined) {
                this.sub_image = data.sub_image;
            }
        }
    }
    get tvid() {
        return pb_1.Message.getField(this, 1);
    }
    set tvid(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get name() {
        return pb_1.Message.getField(this, 2);
    }
    set name(value) {
        pb_1.Message.setField(this, 2, value);
    }
    get sub_image() {
        return pb_1.Message.getWrapperField(this, SubImage, 3);
    }
    set sub_image(value) {
        pb_1.Message.setWrapperField(this, 3, value);
    }
    toObject() {
        const data = {};
        if (this.tvid != null) {
            data.tvid = this.tvid;
        }
        if (this.name != null) {
            data.name = this.name;
        }
        if (this.sub_image != null) {
            data.sub_image = this.sub_image.toObject();
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.tvid !== undefined)
            writer.writeUint32(1, this.tvid);
        if (typeof this.name === "string" && this.name.length)
            writer.writeString(2, this.name);
        if (this.sub_image !== undefined)
            writer.writeMessage(3, this.sub_image, () => this.sub_image.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TerImage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.tvid = reader.readUint32();
                    break;
                case 2:
                    message.name = reader.readString();
                    break;
                case 3:
                    reader.readMessage(message.sub_image, () => message.sub_image = SubImage.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return TerImage.deserialize(bytes);
    }
}
export class TerStats extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("visibilty" in data && data.visibilty != undefined) {
                this.visibilty = data.visibilty;
            }
            if ("scoutablity" in data && data.scoutablity != undefined) {
                this.scoutablity = data.scoutablity;
            }
        }
    }
    get visibilty() {
        return pb_1.Message.getField(this, 1);
    }
    set visibilty(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get scoutablity() {
        return pb_1.Message.getField(this, 2);
    }
    set scoutablity(value) {
        pb_1.Message.setField(this, 2, value);
    }
    toObject() {
        const data = {};
        if (this.visibilty != null) {
            data.visibilty = this.visibilty;
        }
        if (this.scoutablity != null) {
            data.scoutablity = this.scoutablity;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.visibilty !== undefined)
            writer.writeFloat(1, this.visibilty);
        if (this.scoutablity !== undefined)
            writer.writeFloat(2, this.scoutablity);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TerStats();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.visibilty = reader.readFloat();
                    break;
                case 2:
                    message.scoutablity = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return TerStats.deserialize(bytes);
    }
}
export class RoadStats extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("quality" in data && data.quality != undefined) {
                this.quality = data.quality;
            }
        }
    }
    get quality() {
        return pb_1.Message.getField(this, 1);
    }
    set quality(value) {
        pb_1.Message.setField(this, 1, value);
    }
    toObject() {
        const data = {};
        if (this.quality != null) {
            data.quality = this.quality;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.quality !== undefined)
            writer.writeFloat(1, this.quality);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RoadStats();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.quality = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return RoadStats.deserialize(bytes);
    }
}
export class TerImageSeq extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2, 3, 4], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("comp_image" in data && data.comp_image != undefined) {
                this.comp_image = data.comp_image;
            }
            if ("tmag" in data && data.tmag != undefined) {
                this.tmag = data.tmag;
            }
            if ("zval" in data && data.zval != undefined) {
                this.zval = data.zval;
            }
            if ("indx" in data && data.indx != undefined) {
                this.indx = data.indx;
            }
        }
    }
    get comp_image() {
        return pb_1.Message.getWrapperField(this, ImageAry, 1);
    }
    set comp_image(value) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get tmag() {
        return pb_1.Message.getRepeatedWrapperField(this, TerImage, 2);
    }
    set tmag(value) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    get zval() {
        return pb_1.Message.getField(this, 3);
    }
    set zval(value) {
        pb_1.Message.setField(this, 3, value);
    }
    get indx() {
        return pb_1.Message.getField(this, 4);
    }
    set indx(value) {
        pb_1.Message.setField(this, 4, value);
    }
    toObject() {
        const data = {};
        if (this.comp_image != null) {
            data.comp_image = this.comp_image.toObject();
        }
        if (this.tmag != null) {
            data.tmag = this.tmag.map((item) => item.toObject());
        }
        if (this.zval != null) {
            data.zval = this.zval;
        }
        if (this.indx != null) {
            data.indx = this.indx;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.comp_image !== undefined)
            writer.writeMessage(1, this.comp_image, () => this.comp_image.serialize(writer));
        if (this.tmag !== undefined)
            writer.writeRepeatedMessage(2, this.tmag, (item) => item.serialize(writer));
        if (this.zval !== undefined)
            writer.writePackedInt32(3, this.zval);
        if (this.indx !== undefined)
            writer.writePackedInt32(4, this.indx);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TerImageSeq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.comp_image, () => message.comp_image = ImageAry.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.tmag, () => pb_1.Message.addToRepeatedWrapperField(message, 2, TerImage.deserialize(reader), TerImage));
                    break;
                case 3:
                    message.zval = reader.readPackedInt32();
                    break;
                case 4:
                    message.indx = reader.readPackedInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return TerImageSeq.deserialize(bytes);
    }
}
export class ModImage extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("mndx" in data && data.mndx != undefined) {
                this.mndx = data.mndx;
            }
            if ("name" in data && data.name != undefined) {
                this.name = data.name;
            }
            if ("sub_image" in data && data.sub_image != undefined) {
                this.sub_image = data.sub_image;
            }
            if ("p_color" in data && data.p_color != undefined) {
                this.p_color = data.p_color;
            }
        }
    }
    get mndx() {
        return pb_1.Message.getField(this, 1);
    }
    set mndx(value) {
        pb_1.Message.setField(this, 1, value);
    }
    get name() {
        return pb_1.Message.getField(this, 2);
    }
    set name(value) {
        pb_1.Message.setField(this, 2, value);
    }
    get sub_image() {
        return pb_1.Message.getWrapperField(this, SubImage, 3);
    }
    set sub_image(value) {
        pb_1.Message.setWrapperField(this, 3, value);
    }
    get p_color() {
        return pb_1.Message.getField(this, 5);
    }
    set p_color(value) {
        pb_1.Message.setField(this, 5, value);
    }
    toObject() {
        const data = {};
        if (this.mndx != null) {
            data.mndx = this.mndx;
        }
        if (this.name != null) {
            data.name = this.name;
        }
        if (this.sub_image != null) {
            data.sub_image = this.sub_image.toObject();
        }
        if (this.p_color != null) {
            data.p_color = this.p_color;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.mndx !== undefined)
            writer.writeUint32(1, this.mndx);
        if (typeof this.name === "string" && this.name.length)
            writer.writeString(2, this.name);
        if (this.sub_image !== undefined)
            writer.writeMessage(3, this.sub_image, () => this.sub_image.serialize(writer));
        if (this.p_color !== undefined)
            writer.writeUint32(5, this.p_color);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ModImage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.mndx = reader.readUint32();
                    break;
                case 2:
                    message.name = reader.readString();
                    break;
                case 3:
                    reader.readMessage(message.sub_image, () => message.sub_image = SubImage.deserialize(reader));
                    break;
                case 5:
                    message.p_color = reader.readUint32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return ModImage.deserialize(bytes);
    }
}
export class ModImageSeq extends pb_1.Message {
    constructor(data) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], []);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("mblk" in data && data.mblk != undefined) {
                this.mblk = data.mblk;
            }
            if ("model" in data && data.model != undefined) {
                this.model = data.model;
            }
        }
    }
    get mblk() {
        return pb_1.Message.getWrapperField(this, ImageAry, 1);
    }
    set mblk(value) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get model() {
        return pb_1.Message.getRepeatedWrapperField(this, ModImage, 2);
    }
    set model(value) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    toObject() {
        const data = {};
        if (this.mblk != null) {
            data.mblk = this.mblk.toObject();
        }
        if (this.model != null) {
            data.model = this.model.map((item) => item.toObject());
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.mblk !== undefined)
            writer.writeMessage(1, this.mblk, () => this.mblk.serialize(writer));
        if (this.model !== undefined)
            writer.writeRepeatedMessage(2, this.model, (item) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ModImageSeq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.mblk, () => message.mblk = ImageAry.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.model, () => pb_1.Message.addToRepeatedWrapperField(message, 2, ModImage.deserialize(reader), ModImage));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return ModImageSeq.deserialize(bytes);
    }
}
